// Code generated by mockery v2.53.3. DO NOT EDIT.

package account

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: accountNumber
func (_m *MockRepository) Get(accountNumber string) (Account, error) {
	ret := _m.Called(accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Account, error)); ok {
		return rf(accountNumber)
	}
	if rf, ok := ret.Get(0).(func(string) Account); ok {
		r0 = rf(accountNumber)
	} else {
		r0 = ret.Get(0).(Account)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - accountNumber string
func (_e *MockRepository_Expecter) Get(accountNumber interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", accountNumber)}
}

func (_c *MockRepository_Get_Call) Run(run func(accountNumber string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 Account, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(string) (Account, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
