// Code generated by mockery v2.53.3. DO NOT EDIT.

package cbs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function with given fields: ctx
func (_m *MockService) GetStatus(ctx context.Context) (Status, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (Status, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) Status); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(Status)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetStatus(ctx interface{}) *MockService_GetStatus_Call {
	return &MockService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockService_GetStatus_Call) Run(run func(ctx context.Context)) *MockService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetStatus_Call) Return(_a0 Status, _a1 error) *MockService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetStatus_Call) RunAndReturn(run func(context.Context) (Status, error)) *MockService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
