name: My Service Configurations
version: 1.0.0
configs:
  app:
    name: "bankkrud-be-krudapp"
    version: "1.0.0"
    env: "development"
    port: 4000
  postgres:
    dsn: "host=aws-1-ap-southeast-1.pooler.supabase.com user=postgres.qkjhplvloqptlzfalrfm password=PMinUwr6d689pMTz dbname=postgres port=5432 pool_mode=session sslmode=disable TimeZone=Asia/Jakarta"
  redis:
    addr: "redis-15912.crce185.ap-seast-1-1.ec2.redns.redis-cloud.com:15912"
    username: "default"
    password: "mmuFriVXqwC9vLgbt09PYbvBMwgZJeMm"
    db: 0
  token:
    secret: "_jwt_secret_"
    headerKid: "ID-001"
    duration: "5m"
  dbd:
    addr: "https://9effb722-855d-4060-8444-ee2dc5d036d1.mock.pstmn.io"
    username: "Administrator"
    password: "manage"
  cbs:
    addr: "https://9bd3b06d-e18c-45b6-8aa9-cc7297cf9b48.mock.pstmn.io"
    username: "superapps"
    password: "qKb365UykBd9vXpK"
  tracing:
    otlpHttpEndpoint: "localhost:4318" # jaeger
    otlpLogHttpEndpoint: "localhost:3100" # loki
    metricReaderInterval: 1m
