services:
  alloy:
    container_name: grafana-alloy
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    volumes:
      - ${BANKKRUD_BE_KRUDAPP_PATH}/logs/app.log:/var/log/app.log
      - ${BANKKRUD_BE_KRUDAPP_PATH}/grafana/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    networks:
      - grafana-network
  loki:
    container_name: grafana-loki
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-network
  prometheus:
    container_name: grafana-prometheus
    image: prom/prometheus:v3.7.2
    environment:
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://localhost:9090/api/v1/otlp/v1/metrics
      - OTEL_TRACES_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
    volumes:
      - ${BANKKRUD_BE_KRUDAPP_PATH}/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.enable-otlp-receiver
    ports:
      - "9090:9090"
    networks:
      - grafana-network
  grafana:
    container_name: grafana-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    networks:
      - grafana-network

networks:
  grafana-network:
    driver: bridge
