// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/infra/api"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/infra/http/handler"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/infra/http/server"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/infra/service"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/infra/storage/repo"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/config"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/db/postgres"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/db/redis"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/httpclient"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/validation"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/authentication"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/tapmoney"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/transaction"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/transfer"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/user"
)

// Injectors from wire.go:

func initKrudApp(cfg *config.Configs) *krudApp {
	echoEcho := echo.New()
	validator := validation.New()
	cbsStatusAPI := api.NewCBSStatusAPI()
	db := postgres.New(cfg)
	transactionRepo := repo.NewTransactionRepo(db)
	client := httpclient.New()
	paymentGateway := api.NewPaymentGateway(cfg, client)
	cbsAccountAPI := api.NewCBSAccountAPI()
	usecase := tapmoney.NewUsecase(cbsStatusAPI, transactionRepo, paymentGateway, cbsAccountAPI)
	tapMoneyHandler := handler.NewTapMoneyHandler(validator, usecase)
	cbsTransferAPI := api.NewCBSTransferAPI()
	transferUsecase := transfer.NewUsecase(cbsStatusAPI, transactionRepo, cbsAccountAPI, cbsTransferAPI)
	transferHandler := handler.NewTransferHandler(validator, transferUsecase)
	redisClient := redis.New(cfg)
	userRepo := repo.NewUserRepo(cfg, db, redisClient)
	authService := service.NewAuthService(cfg)
	authenticationUsecase := authentication.NewUsecase(userRepo, authService)
	authenticationHandler := handler.NewAuthenticationHandler(validator, authenticationUsecase)
	userUsecase := user.NewUsecase(userRepo, authService, cbsAccountAPI)
	userHandler := handler.NewUserHandler(validator, userUsecase)
	transactionUsecase := transaction.NewUsecase(transactionRepo)
	transactionHandler := handler.NewTransactionHandler(validator, transactionUsecase)
	httpServer := server.NewHTTP(cfg, echoEcho, tapMoneyHandler, transferHandler, authenticationHandler, userHandler, transactionHandler)
	mainKrudApp := newKrudApp(httpServer, db, redisClient)
	return mainKrudApp
}
