// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/adapter/api"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/adapter/http/handler"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/adapter/http/server"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/adapter/storage/repo"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/config"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/db/postgres"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/httpclient"
	"go.bankkrud.com/bankkrud/backend/krudapp/internal/pkg/validation"
	tapmoney2 "go.bankkrud.com/bankkrud/backend/krudapp/internal/usecase/tapmoney"
)

// Injectors from wire.go:

func initTapMoney(cfg *config.Configs) *tapmoney {
	echoEcho := echo.New()
	validator := validation.New()
	client := httpclient.New()
	cbsAuth := api.NewCBS(cfg, client)
	cbsStatusAPI := api.NewCBSStatusAPI(cfg, client, cbsAuth)
	db := postgres.New(cfg)
	transactionRepo := repo.NewTransactionRepo(db)
	paymentGateway := api.NewPaymentGateway(cfg, client)
	accountAPI := api.NewAccountAPI(cfg, client, cbsAuth)
	usecase := tapmoney2.NewUsecase(cbsStatusAPI, transactionRepo, paymentGateway, accountAPI)
	tapMoneyHandler := handler.NewTapMoneyHandler(validator, usecase)
	httpServer := server.NewHTTP(cfg, echoEcho, tapMoneyHandler)
	mainTapmoney := newTapMoney(httpServer, db)
	return mainTapmoney
}
