// Code generated by mockery v2.53.3. DO NOT EDIT.

package pocket

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetByAccountNumber provides a mock function with given fields: ctx, accountNumber
func (_m *MockRepository) GetByAccountNumber(ctx context.Context, accountNumber string) (Pocket, error) {
	ret := _m.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountNumber")
	}

	var r0 Pocket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Pocket, error)); ok {
		return rf(ctx, accountNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Pocket); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		r0 = ret.Get(0).(Pocket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByAccountNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountNumber'
type MockRepository_GetByAccountNumber_Call struct {
	*mock.Call
}

// GetByAccountNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockRepository_Expecter) GetByAccountNumber(ctx interface{}, accountNumber interface{}) *MockRepository_GetByAccountNumber_Call {
	return &MockRepository_GetByAccountNumber_Call{Call: _e.mock.On("GetByAccountNumber", ctx, accountNumber)}
}

func (_c *MockRepository_GetByAccountNumber_Call) Run(run func(ctx context.Context, accountNumber string)) *MockRepository_GetByAccountNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByAccountNumber_Call) Return(_a0 Pocket, _a1 error) *MockRepository_GetByAccountNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByAccountNumber_Call) RunAndReturn(run func(context.Context, string) (Pocket, error)) *MockRepository_GetByAccountNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
